#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
camera_fx: 718.856
camera_fy: 718.856
camera_cx: 607.1928
camera_cy: 185.2157

camera_k1: 0.0
camera_k2: 0.0
camera_k3: 0.0
camera_p1: 0.0
camera_p2: 0.0

Camera.width: 1241
Camera.height: 376

# Camera frames per second 
camera_fps: 10.0

# stereo baseline times fx
camera_baseline: 386.1448

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
camera_rgb_encoding: 1

# Close/Far threshold. Baseline times.
ThDepth: 35

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor/nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor/scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor/nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor/iniThFAST: 20
ORBextractor/minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 1
Viewer.PointSize: 2
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -100.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

